"""password column edited to password_hush

Revision ID: 1ff938166593
Revises: af4eadbe1d7d
Create Date: 2022-05-16 14:50:37.828103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff938166593'
down_revision = 'af4eadbe1d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hush', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hush')
    # ### end Alembic commands ###
